version: '3'
services:
  app:
    # image: your-dockerhub-username/your-image-name:latest
    image: camilleivins/keepr:latest
    env_file:
      - keepr-env
    ports:
      - "7045:80"
    restart: unless-stopped